# -*- coding: utf-8 -*-
"""actividad_01_binomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GchJbGBzEeh_E7Wgt_ck25SJhdjDprnp
"""


"""

Esta función calcula el coeficiente binomial de dos números n y k.
Para los cuales se les cálcula el factorial previamente; n! ^ k!.

"""
def factorial(n):
  if n<0:
    return "el número no puede ser negativo"
  if type(n)==float:
    return "el número no puede ser real"
  if n==0:
    return 1
  else:

    return factorial(n-1)*n

def binomial(n,k):

  binom = factorial(n)//(factorial(k)*factorial(n-k))

  return binom

binomial(5,3)

