# -*- coding: utf-8 -*-
"""Copia de Copia de Actividad_08_integracion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12f_rSV6RdbvPf5YDbwzW3B6pcCEMr7nv

# Actividad 
1. Elaborar un programa en python que permita calcular la integral de una función entre el intervalo a, b. para ello debera realizar lo siguiente:

## Realizar en notebook de collab
- Deducir la ecuación general del metodo del trapecio.
- Construir un funcion llamada integral_trapz que reciba como argumento una función y el intervalo a, b. El numero de intervalos N será un argumento opcional, 
  defina por defecto N=10. La función deberá retornar el valor de la integral.  
- Comparar la solución con la libreria de scipy https://docs.scipy.org/doc//scipy-1.4.1/reference/generated/scipy.integrate.trapz.html

## Construir un programa en python con la función anterior que realice lo siguiente:  

- Generalice el programa para que la funcion pueda ser pasada como parametro en terminal, junto con el parametro a, b. la ejecucion debera ser:
  python integral func a b, Ejemplo de ejcucion:
  python x**2+1 1 5  

Para pasar los parametros consulte la libreria sys de python.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import trapz

#trapecio
f=lambda x:x**2
a=0
b=1
N=5
h=(b-a)/N
x=np.linspace(a,b,N+1)

A= (f(x[0])+f(x[-1]))*0.5*h+f(x[1:-1]).sum()*h
print(h,A)



trapz(f(x),x)

def integral_trap(fun,a,b,N=10):
  h=(b-a)/N
  x=np.linspace(a,b,N+1)
  A = (f(x[0])+f(x[-1]))*0.5*h+f(x[1:-1]).sum()*h
  return A

funcion='x**2+np.log(x**2+1)'
f=lambda x: eval(funcion)

print(integral_trap(f,0.1,1,N=5))
x=np.linspace(0.1,1,N+1)

trapz(f(x),x,dx=h)

