# -*- coding: utf-8 -*-
"""Actividad_DiagonoalizacionMatrices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZ8s43SIVxZHCdGLfOsVM-AI6PgMxnWo

# Autovalores, autovectores, polinomio caracteristico, diagonalización

| Librería | Función | Explicación |
| --- | --- | --- |
| numpy | numpy.linalg.eig | Calcula los autovalores y autovectores derechos de una matriz cuadrada |
| numpy | numpy.linalg.eigh | Calcula los autovalores y autovectores de una matriz hermítica compleja o simétrica real |
| numpy | numpy.poly | Calcula el polinomio característico de una matriz |
| sympy | sympy.Matrix.eigenvals | Calcula los autovalores de una matriz simbólica |
| sympy | sympy.Matrix.eigenvects | Calcula los autovalores y autovectores de una matriz simbólica |
| sympy | sympy.Matrix.charpoly | Calcula el polinomio característico de una matriz simbólica |

Calcular el polinomio caracteristico, los  autovalores y autvectores propios de la siguiente matrices, comprobar con la solucion analitica:

1. 
\begin{bmatrix}
1 & -1 & 4 \\
3 & 2 & -1 \\
2 & 1 & -1
\end{bmatrix}


2. \begin{bmatrix}
3 & -5 \\
1 & -1 \\
\end{bmatrix}

# Diagonalizacion 
Una matriz cuadrada $A$ es diagonalizable si y solo si cada autovalor $\lambda$ de multiplicidad $m$ produce exactamente $m$ autovectores básicos; es decir, si y solo si la solución general del sistema $(A-I\lambda)\vec{x}=0$ tiene exactamente $m$ parámetros.


Para diagonalizar una matriz $A$, se necesita encontrar una matriz invertible $P$ tal que $P^{-1}AP$ sea una matriz diagonal $D$. Esto significa que las columnas de $P$ son los autovectores de $A$ y los elementos de la diagonal de $D$ son los autovalores correspondientes de $A$.

Encuentre la matrix diagnonal para las matrices anteriores.

Actividad 2. 

Considere la ecuación cuadrática $x^2-4xy+3y=6$, esta ecuación cuadrática se corresponde a una hiperbola, la cual puede ser escrita en forma matricial como sigue:

$A\vec{v} \cdot \vec{v}=6$, donde $\vec{v}=(x, y)$ y A es una matrix simetrica, 

\begin{equation}
A=\begin{bmatrix}
1 & -2 \\
-2 & 3 \\
\end{bmatrix}
\end{equation}

1. Realice un grafico que represente la hyperbola







- Diagonalice A, para ello construya la matrix Q de autovectores ortoganales 
tal que $D=Q^{T}AQ$, en este caso se dice que A es diagonalizable ortogonalmente, donde $A=QDQ^T$.

- Aplique el resultado de la siguiente demostración para encontrar una nueva hyperbola en una  nueva base

\begin{equation}
QDQ^T \vec{v} \cdot \vec{v} = d
\end{equation}


\begin{equation}
Q(DQ^T\vec{v}) \cdot \vec{v} = (DQ^T\vec{v}) \cdot (Q^T\vec{v})=d
\end{equation}


\begin{equation}
(DQ^T\vec{v}) \cdot (Q^T\vec{v})=d
\end{equation}


Sea $u=Q^T\vec{v}$

Luego :


\begin{equation}
(D\vec{u}) \cdot \vec{u}=d
\end{equation}

donde $\vec{u}=(x', y')$, tal que $D\vec{u} \cdot \vec{u}=d$ es una nueva hyperbola
"""

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

M1=  np.array([[1,-1,4],[3,2,-1],[2,1,-1]])
M1

np.linalg.eig(M1)

P= np.array([[ 0.40824829,  0.57735027,  0.23570226],
        [ 0.81649658, -0.57735027, -0.94280904],
        [ 0.40824829, -0.57735027, -0.23570226]])
P

D= np.linalg.inv(P)@M1@P
D

M2 = np.array([[3,-5],[1,-1]])
M2

np.linalg.eig(M2)

P_= np.array([[0.91287093+0.j        , 0.91287093-0.j        ],
        [0.36514837-0.18257419j, 0.36514837+0.18257419j]])

D = np.linalg.inv(P_)@M2@P_
D

hip = lambda x: np.sqrt(2-(2/3*x)**2-(x**2)/3)+2/3*x 
x = np.linspace(2,-10,100)

plt.plot(x,hip(x))