# -*- coding: utf-8 -*-
"""Actividad_integral.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7cVa1VWt5Tf5QdruvGJs7W8NIQyM2-I

# Actividad
Elaborar un programa en python que permita calcular la integral de una función entre el intervalo a, b. para ello debera realizar lo siguiente:
## Realizar en notebook de collab
Deducir la ecuación general del metodo del trapecio.
Construir un funcion llamada integral_trapz que reciba como argumento una función y el intervalo a, b. El numero de intervalos N será un argumento opcional, defina por defecto N=10. La función deberá retornar el valor de la integral.
Comparar la solución con la libreria de scipy https://docs.scipy.org/doc//scipy-1.4.1/reference/generated/scipy.integrate.trapz.html
### Construir un programa en python con la función anterior que realice lo siguiente:
Generalice el programa para que la funcion pueda ser pasada como parametro en terminal, junto con el parametro a, b. la ejecucion debera ser: python integral func a b, Ejemplo de ejcucion: python x**2+1 1 5
Para pasar los parametros consulte la libreria sys de python.
"""

import numpy as np
from scipy.integrate import trapz

f = lambda x: x**2

def integral(f,a,b,N=10):


  h= (b-a)/N
  interval = np.arange(a,b,h)

  F= f(interval)
  suma = np.sum(F)
  suma
  Area= (h/2)*(f(a)+f(b))+h*suma
  return Area

integral(f,0,1,10)

a= 0
b= 1
N = 10
x = np.linspace(a,b,N)
integ= trapz(f(x),x)
integ