<a href="https://colab.research.google.com/github/hernansalinas/autogradesMetodosComputacionales/blob/main/Laboratorios_Taller/Lab01_python_basico01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Laboratorio 01
### Métodos computacionales para físicos  y astrónomos
### Universidad de Antioquia
### Profesores:
### Hernan D. Salinas Jiménez
### Juan Marcos Marin


In [7]:
# Ejecutar esta celda antes de cada laboratorio
!git clone https://github.com/hernansalinas/autogradesMetodosComputacionales.git
path1=f"autogradesMetodosComputacionales/Laboratorios_Taller/libs/"
path2=f"autogradesMetodosComputacionales/Laboratorios_Taller/libs/Lab_autotesting01/"
%run -i {path1}libUnitTest.py

Cloning into 'autogradesMetodosComputacionales'...
remote: Enumerating objects: 1160, done.
remote: Counting objects: 100% (222/222), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 1160 (delta 135), reused 138 (delta 58), pack-reused 938 (from 1)
Receiving objects: 100% (1160/1160), 40.05 MiB | 30.95 MiB/s, done.
Resolving deltas: 100% (710/710), done.


# Operaciones básicas en python.


### Definicion de variables
1. Definir una variable x tipo entero.
2. Definir una variable y tipo float
3. Definir una variable z tipo string.

In [8]:
# Defina la variables en esta celda

x = int(3)
y = float(5.5)
z = "cadena"

In [9]:
# Ejecute la presente celda para probar su solucion
%run -i {path2}/test01.py



###  Creación de Funciones
4. Crear una función con el nombre mul_lambda tipo lambda que multiple dos enteros, el resultado deberá ser un número entero.  

Ejemplo de ejecución:

```python

mul_lambda(a,b)
#donde a, y b son numeros enteros

```


5. Crear una función explicita con el nombre de sum_int, que realice la suma de dos números enteros

Ejemplo de ejecución:

```python

sum_int(a,b)
#donde a, y b son numeros enteros

```



In [10]:
# Escriba las funciones en esta celda


# Función producto tipo lambda
mul_lambda = lambda a,b: a * b

print(int(mul_lambda(10,2)))


# Función de suma explícita

def sum_int(a, b):
  """
  Docstring!
  """

  return a + b


print("Suma de enteros: ", sum_int(4,9))

20
Suma de enteros:  13


In [11]:
%run -i {path2}/test02.py


###  Números complejos

6. Defina un número complejo w.
7. Retorne la parte imaginaria de w, almacenela en una variable w_img
8. Retorne la parte real de w, almacenela en una variable w_real.
9. Retorne el complejo conjugado de w, almacenla en una varible w_con.


In [12]:
# Escriba acá su solución

w = 10 + 11j
w_real = w.real
w_img = w.imag
w_con = w.conjugate()

print("Complejo: ", w, "Re(w): ", w_real, "Im(w): ", w_img,
      "Conjugado w: ", w_con)

Complejo:  (10+11j) Re(w):  10.0 Im(w):  11.0 Conjugado w:  (10-11j)


In [13]:
%run -i {path2}/test03.py

###  Listas

10.0  Construir una lista L con las variables usadas hasta acá y los resultados de las funciones.

L=[x,y,z,mul_lambda, sum_int,w, w_img, w_real, w_con ]

11.0 Invierta la lista y almacene en una variable L_reverse

12.0 Almacene los indices impares de la lista, L_imp

13.0 Almacene los indicies pares de la lista, L_par

14.0 Almacena en una nueva variable llamada Lnew con la lista L, modifique el indice 5 de la lista L con la palabra "hello world"


In [14]:
# Escriba en esta celda su solucion

L = [x,y,z,mul_lambda, sum_int,w, w_img, w_real, w_con]

L_reverse = L[::-1]  # Invertir el orden de la lista.

L_imp = L[1::2]  # Índices impares de la lista.

L_par = L[::2]  # Índices pares de la lista.

Lnew = L
Lnew[5] = "hello world"

Lnew

[3,
 5.5,
 'cadena',
 <function __main__.<lambda>(a, b)>,
 <function __main__.sum_int(a, b)>,
 'hello world',
 11.0,
 10.0,
 (10-11j)]

In [15]:
%run -i {path2}/test04.py

SyntaxError: expected 'except' or 'finally' block (test04.py, line 48)

###  Tuplas

15.0 Definir una tupla con 5 elementos almacenda en la variable Tup, los primeros 3 tipo string y los ultimos dos, tipo float.

In [16]:
# Escriba en esta celda su solucion

Tup = ("programar", "es", "divertido", 100.0, 100.0)

In [17]:
 %run -i {path2}/test05.py

###  Set
16.0 Defina una variable tipo set llamada  D con los primeros 11 numeros primos, consultalos en la red. Notese que pasa en este variables cuando alguno de los elementos se repite

17.0 Defina una variable tipo set llamada E con los números naturales del 1 al 20.

18.0 Calcule la unión  y almacenela en una variable U.

19.0 Calcule la intersección y almacenela en una variable I


In [18]:
# Escriba acá su solución

D = {2, 3, 5, 7, 11, 17, 19, 23, 29, 31, 37}

E = {i for i in range(1, 21)}

U = D | E  # Unión de los conjuntos D y E.

I = D & E  # Intersección de los conjuntos D y E.

In [19]:
 %run -i {path2}/test06.py















###  Diccionarios
20.0 Construir un diccionario con 5 elementos cuya clave es el nombre del autor y valor el nombre del libro. Almacenarlo en una variable dicc.





In [20]:
# Escriba acá su solución

dicc = {'Ken Follet':"Los pilares de la Tierra", 'Frank Kafka': "Carta al \
padre", 'Stieg Larsson':"Los hombres que no amaban a las mujeres", 'Charles \
Dickens':"Oliver Twis", 'Alexander Dumas':"El Conde de Montecristo"}

dicc

{'Ken Follet': 'Los pilares de la Tierra',
 'Frank Kafka': 'Carta al padre',
 'Stieg Larsson': 'Los hombres que no amaban a las mujeres',
 'Charles Dickens': 'Oliver Twis',
 'Alexander Dumas': 'El Conde de Montecristo'}

In [21]:
 %run -i {path2}/test07.py


####  Ciclos y condicionales

21.0  Cálculo de $\pi$. Empleando la siguiente seria :

\begin{equation}
\frac{\pi}{4} = 1 -\frac{1}{3}+\frac{1}{5}-\frac{1}{7}+\frac{1}{9}-...
\end{equation}

Construya una función llamada pi_number en el que entrado el valor de k,(número de términos de la serie ) calcule el valor de pi. Si k es negativo deberá retornar un error como una variable tipo string.

Ejemplo de ejecución:
```python
pi_number(10)
```

In [64]:
# Escriba acá su solución

def pi_number(k: int):

  """
  La función estima el número de pi por la serie
  de Leibniz.
  """

  if type(k) == int and k >= 0:

    aprox_pi = 0

    for i in range(0, k + 1):
      termino = ((-1) ** (i + 2)) * (1 / (2 * i + 1))
      aprox_pi += termino

    return 4 * aprox_pi

  elif type(k) == int and  k < 0:
    return "Error"
  else:
    return "Error"



print(pi_number(1000000))

3.1415936535887745


In [61]:
 %run -i {path2}/test08.py