# -*- coding: utf-8 -*-
"""actividad_01 actualizada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfOehn4B7oAsZhNOzqgeEA0U0MTgKSXd
"""

def doble_factorial(n):
  if n<0:
    return ("Necesito un número positivo")
  elif n==0:
    return 1
  if isinstance(n,int):
    b=1
    while n>0:
      b=b*n
      n-=2
    return b

  else:
    return ("Necesito que la variable ingresada sea entero")




print(f"El doble factorial de 6 es {doble_factorial(6)}")
print(f"El doble factorial de 7 es {doble_factorial(7)}")
print(f"El doble factorial de 8 es {doble_factorial(8)}")

"""El de abajo no está terminado:

"""

def lucas(n):
  a=2
  b=1
  for i in range(1,n,1):
    siguiente=a+b
    a=b
    b=siguiente

  return siguiente

print(f"El término noveno de la sucesión de lucas es {lucas(9)}")
print(f"El término décimo de la sucesión de lucas es {lucas(10)}")
print(f"El término onceavo de la sucesión de lucas es {lucas(11)}")

def binomial(n,k):
  if isinstance(n,int)and isinstance(k,int):
      a=1
      r=(factorial(n))/(factorial(k)*factorial(n-k))
      r=int(r)
      return r

  else:
    return ("Necesito que las variables ingresadas sean enteros")

print(f"El coeficiente binomial de 6 y 4 es {binomial(6,4)}")
print(f"El coeficiente binomial de 7 y 2 es {binomial(7,2)}")