# -*- coding: utf-8 -*-
"""actividad_01_lucas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xZ3hsGS6O8LX55IBSkcw8MWrswLhtcHd
"""

def lucas(n):
  if n==0:
    return 2
  if n==1:
    return 1
  else:
    l=[2,1]
    for i in range(2,n+1):
      lucas=l[i-1]+l[i-2]
      l.append(lucas)
    return print("El n-ésimo término de la sucesión es",l[n], "\nLa sucesión hasta el n-ésimotérmino es ",l)

lucas(10)