# -*- coding: utf-8 -*-
"""Actividad_01_enteros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwCab1Ebyfu-TM8MZgGU2GzD5s9T5cBR

*1.  Escribir un programa que pida al usuario dos números enteros , y muestre por pantalla el cociente y el residuo entre ellos.*
"""

a=int(input("Por favor ingrese un número "))
b=int(input("Ingrese otro número "))
if b==0:
    print("Error, división sobre cero no es válida")
else:
    c=a/b
    d=a%b
    print ("El resultado de la división es ",c)
    print("El resultado del residuo es ",d)