# -*- coding: utf-8 -*-
"""actividad_01_doble_factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hhy70qmZUQW4AlGTIbeQeYo33Ovuec99
"""

def doble_factorial(n):
  suma=1
  for i in range(n,0,-2):
    suma*=i

  return suma
doble_factorial(9)