# -*- coding: utf-8 -*-
"""actividad_01_binomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NE4TJmhJSwd2KL2SCCsYpuZapVUq9Qt
"""

def factorial(n):
  count=1
  for i in range(n):
    suma=(n-i)
    count*=suma
    fact=count
  return fact

def binomial(n,k):
  cb=factorial(n)/(factorial(k)*(factorial(n-k)))
  return cb

print(binomial(5,3))
print(binomial(6,4))
print(binomial(7,2))