# -*- coding: utf-8 -*-
"""Lab04_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dDRRnLW6unLjDKUTiTKUOA0akLW-N3Z9
"""

# Initialize Otter
#import otter
#grader = otter.Notebook("Lab04_pandas.ipynb")

# Commented out IPython magic to ensure Python compatibility.
#import otter
import pandas as pd
import numpy as np
# %matplotlib inline
#import otter
import matplotlib.pylab as plt
#grader = otter.Notebook()

"""
**Pregunta  1:** Para los planetas de nuestro sistema solar, construir una serie de pandas  `ds` con indice nombre del planeta y valor la distancia al sol en UA.

Puedes intentanar generarlos con una IA, ejemplo de prompt:

hint:
`Generar un diccionario cuya clave es el nombre del planeta y valor la distancia al sol en UA`


a. Acceder al valor de mercurio y almacenarlo en una variable llamada dM.

b. Acceder al valor de Jupyter y almacenarlo en una variable llamada dJ.

c. Generar una nueva serie con los planetas cuya distancia es menor a 10UA, almacenarla en s"""

dicc={'Mercurio':0.39,'Venus':0.72,'Tierra':1.00,'Marte':1.52,'Júpiter':5.20,'Saturno':9.54,'Urano': 19.22 ,'Neptuno':30.06,'Plutón':39.48}
ds=pd.Series(dicc)

ds

dM=ds[0]
dJ=ds[4]

s=ds[ds<=10]  #o s=ds[0:6]
s

grader.check("q1")

"""**Pregunta 2:**

a. Construir una serie de pandas  `dt`, con indice nombre del planeta y valor el periodo orbital en unidades de periodos terrestres.

b. Construir un dataframe de  pandas `df` con la serie ds y la serie dt, los nombres de las columnas deberán ser:
 `DistanciaSolUA`, `PeriodoUT`, el indice debe ser el nombre del planeta

"""

d={'Mercurio':0.2408,'Venus':0.6152,'Tierra':1.00,'Marte':1.8809,'Júpiter':11.862,'Saturno':29.458,'Urano': 84.01 ,'Neptuno':164.79,'Plutón':247}
dt = pd.Series(d)
d={'DistanciaSolUA':ds,'PeriodoUT':dt}
df=pd.DataFrame(d)
df

grader.check("q2")

"""**Pregunta 3:** El dataset [Temperature_Bogota_Barcelona](https://github.com/hernansalinas/Curso_Metodos_Computacionales/blob/main/Entregas/Parciales/Parcial1/dataset/Temperature_Bogota_Barcelona.csv)
 contiene información de la temperatura (en grados Fahrenheit) promedio de Bogotá y Barcelona desde el año 1995. Para el presente dataset realizar lo siguiente:


 a. Leer el dataset desde el link sugerido.

 b. Eliminar las columnas Month,  day y Unnamed

 c. Adicionar una nueva columna llamada `AvgTempCelcius` con la temperatura en grados celcius. $ C=(F-32)/1.8$


"""

link= 'https://raw.githubusercontent.com/hernansalinas/Curso_Metodos_Computacionales/main/Entregas/Parciales/Parcial1/dataset/Temperature_Bogota_Barcelona.csv'
df=pd.read_csv(link)

df

df=df.drop(columns=['Unnamed: 0','Month','Day'])

df['AvgTempCelcius']=(df['AvgTemperature']-32 )/1.8
df

grader.check("q3")

"""**Pregunta 4** Para el miso data set anterior realizar lo siguiente:

 a. Crear un nuevo data frame llamado df1, con los valores de temperatura de bogota que sean menores que 20 °C.
 b. Crear un nuevo data frame llamado df2, con los valores de temperatura de Barcelona que este entre 10 °C y 20 °C
"""

df1 = df[df['City']=='Bogota'][df['AvgTempCelcius']<20]
df2 = df[df['City']=='Barcelona'][(df['AvgTempCelcius']>10) & (df['AvgTempCelcius'] <20) ]
print(df1.head())
print(df2.head())

grader.check("q4")

"""<!-- BEGIN QUESTION -->

**Pregunta  5** Para el data set df, con todos los valores de Bogota y Barcelona, realizar en misma figura lo siguiente, recuerda poner las unidades y etiquetas respectivas :

 d. Gráfico de AvgTempCelcius como función del año para la ciudad de Bogotá.

 e. Gráfico AvgTempCelcius como funcion del año para la ciudad de Barcelona.
"""

bogota=df[df['City']=='Bogota']
barcelona=df[df['City']=='Barcelona']

plt.figure(figsize=(5,5))
plt.plot(bogota['Year'],bogota['AvgTempCelcius'], label='Bogotá',color='red')
plt.plot(barcelona['Year'],barcelona['AvgTempCelcius'], label='Barcelona',color='blue')
plt.xlabel('Año')
plt.ylabel('Temperatura Promedio (°C)')
plt.title('Temperatura Promedio de Bogotá y Barcelona')
plt.legend()

"""<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Pregunta 5:** ¿Qué puede inferir del gráfico?

Se puede observar que la temperatura de Bogotá se mantiene en un rango más o menos constante, con solo dos mínimos en su temperatura,lo que indica un clima relativamente estable, sin grandes cambios estacionales. Esto se debe gracias a la ubicación de Bogotá, al estar tan cerca del Ecuador tiene temperaturas más estables durante el año, pues la inclinación de la Tierra respecto al Sol es menos pronunciada cerca al ecuador, lo que genera una distribución mas uniforme de radiación solar a lo largo del año.

También se puede observar que no hay una tendencia significativa de calentamiento hasta 2017, donde las temperaturas de Bogotá han comenzadoa aumentar.

Por otro lado, podemos ver que para Barcelo el clima es más variable, marcado por diferencias estacionales, probablemente debido a que está en una latitud más alta que Bogotá, por lo cual se ve más afectada por los cambio estacionales.

Al igual que Bogotá, Barcelona a partir de 2017 empieza a sufrir un cambio en su temperatura, disminuyendo considerablemente repecto a su temperatura promedio.

<!-- END QUESTION -->

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

These are some submission instructions.
"""

# Save your notebook first, then run this cell to export your submission.
grader.export(run_tests=True)