# -*- coding: utf-8 -*-
"""actividad_01_binomial.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKFr4E-l2seNKhWgERVxhq-ekElt5nuN
"""



#Coeficiente binomial
#!/usr/bin/python
def factorial(n):
  fact=1
  for i in range(1,n+1):
    fact*=i
  return fact


def binomial(n,k):
  n_factorial=factorial(n)
  k_factorial=factorial(k)
  l=n-k
  l_factorial=factorial(l)
  coef_bi=(n_factorial)/((k_factorial)*(l_factorial))
  #print(n_factorial, k_factorial, l_factorial, coef_bi)
  print("El coeficiente binomial de (",n,",",k,") es: ",coef_bi)

binomial(6,2)
binomial(6,4)
binomial(3,2)

