# -*- coding: utf-8 -*-
"""actividad_01_doble_factorial.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRAMjPpNPtwIsrbfjKj1ZbRWqoAQ0lSn
"""

#!/usr/bin/python
def doble_factorial(n):
    s=n
    while(n>2):
        n=n-2
        s=s*n
    return(s)

n=7
r=doble_factorial(n)
print("EL doble factorial de",n,"es: ",r)
n=6
r1=doble_factorial(n)
print("EL doble factorial de",n,"es: ",r1)
n=8
r2=doble_factorial(n)
print("EL doble factorial de",n,"es: ",r2)

