# -*- coding: utf-8 -*-
"""actividad_01_lucas.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8xIdVhqEefbAaXxt643cr8a5Be4eaMJ
"""

#SUCESION DE LUCAS


#!/usr/bin/python
def Lucas(n):
#n=int(input("Escribe: "))
  sl=0
  s=[1,3]
  s1=[1]
  s2=[1,3]
  if n==0:
    print("ERROR: La n posición debe ser mayor a uno [n>0]","\n")
  elif n==1:
    print("La suceción de Lucas hasta la posición 1 y el unico elemento es:", s1,"\n")
  elif n==2:
    print("La suceción de Lucas hasta la posición 2 es:",s2,"\n")
    print("El numero en la posición 2 es: ",s[1],"\n")
  else:
    for i in range(1,n-1):
      sl=s[i]+s[i-1]
      s.append(sl)
    print("La suceción de Lucas hasta la posición",n,"es:", s,"\n")
    print("El número ubicado en la posición",n,"es: ",s[i+1],"\n")


Lucas(2)
Lucas(10)
Lucas(0)
Lucas(1)

