# -*- coding: utf-8 -*-
"""actividad_01_enteros.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2BhkbmOG9gQHeF0zgwhQ2qhm6TRTxhn
"""

#!/usr/bin/python
#se le piden dos numeros y nso retorne la divisiòn y el modulo
n=int(input("Entra un primer nùmero entero: "))
b=int(input("Entra un segundo nùmero entero: "))
x=n/b
z=n%b
print("Divisiòn:",x)
print("Residuo",z)

