# -*- coding: utf-8 -*-
"""actividad_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbiEuc2rVXS_Tf7RPXPYjwLtjG3BjXnn

# **Punto 1**
"""

# Punto 1 (4 lineas menos)
print("La siguiente función pide un número natural que devuelve su factorial doble")
n=int(input("Ingrese el número:"))
def doble_factorial(n):
  f=1
  for i in range (n,0,-2):
      f=f*i
  return(f)
print("Resultado:",doble_factorial(n))

"""# **Punto 2**"""

print("Sucesión similar a la de Fibonacci, empieza sumando el 2 y 1")
n=int(input("Ingrese el n-ésimo término de la sucesión:"))
def lucas(n):
  f0=2
  f1=1
  for i in range(n):
    f_nuevo=f0+f1
    f0=f1
    f1=f_nuevo+f0-f1
  return(f0)
print("Resultado:",lucas(n))

"""# **Punto 3**"""

print("La siguiente función calcula el coeficiente binomial")
n=int(input("Ingrese el número de elementos del conjunto:"))
k=int(input("Ingrese el número de formas en las que desea agrupar los elementos:"))
def binomial(n,k):
  f=1
  m=1
  h=1 # para r
  r=n-k
  for i in range (1,n+1):
    f=f*i
  for j in range (1,k+1):
    m=m*j
  for l in range (1,r+1):
    h=h*l
    coef=(f/(m*h))
  return(coef)
print("Resultado:",binomial(n,k))