#+TITLE: Assignment01
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>

In order to run this code, the following packages will be necessesary:
#+begin_src ipython :session asession :exports code :results raw drawer
import numpy as np
import matplotlib.pylab as plt
#+end_src

#+RESULTS:
:results:
# Out[1]:
:end:

* Plotting an electrostatic field

The electrostatic field due to some point source charge $q$ is given by Coulomb's law,
\[
\mathbf{E} = \frac{1}{4\pi \epsilon_0} \frac{q}{r^2} \hat{\mathbf{r}}
\]
where $r$ denotes the distance from the point charge to the field point, vectorially, if the field point is located at $\mathbf{l}$, and the source at $\mathbf{l}'$, then $\mathbf{r} = \mathbf{l} - \mathbf{l}'$. Notice that the above equation for the field yields a two-component equation in a two dimensional space. In such a case we have
\[
E_x = \frac{1}{4\pi \epsilon_0} \frac{q}{r^2} \frac{r_x}{r} = \frac{1}{4\pi \epsilon_0} \frac{q r_x}{r^3}
\]
and a similar expression is true for the $y$ component of the electric field. The electric field abides by the supperposition principle, that is, the field produced by $n$ different source point charges at a single point $P$ is exactly the vector sum of the individual electic fields due to the soure charges. Taking all these facts into account, we can compute the electic field at arbitrarily many points embedded in a two-dimensional space.

Now that the concept has been clarified, we may proceed with the implementation of the algorithm to compute the electric field at some points on a plane. For simplicity we suppose $1 / 4\pi \epsilon_0 = 1$.

The ~electrostatic_field~ routine takes two square numpy arrays, ~_x~ and ~_y~, as an input; these arrays encode a grid of position vectors, viz., the $x$ and $y$ components of some number of evenly spaced points on a square region of the plane (the amount of points is defined by the user). Its output will be two numpy arrays, ~E_x~ and ~E_y~, with the values of electrostatic field at each initailly given point.

We only require one more input, which is the charge and the position of the sources; we may encode this information in a dictionary with charges as keys and tuples representing the positions of each spurce charge as items. We can read this information by defining a list ~l~, whose elements are tuples containing every key on the original dictionary, assosiated with its respective item, i.e., tuples of the form ~(key, item)~; recall that, in this case, each item is itself a tuple. To create this list we turn to the method ~dict.items()~, and turn the resulting object into a list by applying the method ~list()~ on it. The rest of the process comes down to defining lists of the same length as ~l~, which are then assigned its respective value in a while loop. We thus obtain three lists with the same length: ~charges~, ~source_x_positions_list~, and ~source_y_positions_list~.

Now the computation of the electric field at every point encoded in the two initial arrays, ~_x~ and ~_y~, can be easily carried out by abstraction using numpy arrays. We define two square arrays of the same order as ~_x~ and ~_y~, namely ~E_x~ and ~E_y~; these arrays have initialy zero values, for we are then going to sum over all the electrostatic fields produced by the different charges, tying in with the supperposition principle. We use a while loop to iterate through all the values in the list of charges, x positions, and y positions, which correspond to the sources and then proceed to compute the distance components as ~delta_pos_x~ and ~delta_pos_y~, the magnitude of the ditance as ~R~, and the components of the electrostatic field as the sum of its current value with the value given by Coulomb's law for each charge in the list of charges.
#+begin_src ipython :session asession :exports code :results raw drawer
sources = {1: (-1,0), 1.1: (1,0), -1: (0,1), -1.1: (0,-1)}

def electrostatic_field(_x, _y) :
    l = list(sources.items())
    charges, source_x_positions_list, source_y_positions_list = [0]*len(l), [0]*len(l), [0]*len(l)

    i = 0
    while i < len(l) :
        charges[i], (source_x_positions_list[i], source_y_positions_list[i]) = l[i]
        i += 1

    n, m = np.shape(_y) # n and m are the same number, for _y is a square matrix, as is _x
    E_x, E_y = np.zeros((n,n)), np.zeros((n,n))

    i = 0
    while i < len(charges) :
        delta_pos_x = _x - source_x_positions_list[i]
        delta_pos_y = _y - source_y_positions_list[i]
        R = np.sqrt(delta_pos_x**2 + delta_pos_y**2)

        E_x += charges[i]*delta_pos_x/R**3
        E_y += charges[i]*delta_pos_y/R**3
        i += 1

    return E_x, E_y
#+end_src

#+RESULTS:
:results:
# Out[22]:
:end:

The bulk of the ~graph~ routine is to create a two dimensional partition of the plane area defined by the user with the parameter ~boxlength~. Actually, ~boxlength~ denotes half the length of the side of the figure, which is always going to be centred at (0,0); hence we must evenly partition an interval [-boxlength, boxlength]. Such a partition is given by ~i*2*boxlength/(num_partitions-1) - boxlength~ for i from 0 to the desired number of partitions. We must use the resulting set of numbers in a square matrix with /repeating rows/, which represents the x component of the position of a square, evenly spaced grid of points. The transpose of the aforementioned matrix is the y component of the same grid of points. These matrices are then used to compute the electrostatic field.

Now we only need to use the utilities of ~matplotlib~ to graph the electrostatic field of a configuration of source point charges.
#+begin_src ipython :session asession :exports both :results raw drawer
%config InlineBackend.figure_format = 'svg'

def graph(boxlength, num_partitions) : # boxlength represents half the length of the side
    x = [[i*2*boxlength/(num_partitions-1) - boxlength for i in range(num_partitions)] for k in range(num_partitions)]
    y = x[:]
    x, y = np.array(x), np.array(y).T
    E_x, E_y = electrostatic_field(x, y)

    plt.gca().set_aspect('equal', adjustable='box')
    plt.streamplot(x, y, E_x, E_y, color='k', arrowstyle ='->')
    plt.xlabel('$x$')
    plt.ylabel('$y$')
    plt.show()

# execute the code
graph(boxlength = 2,
      num_partitions = 20)
#+end_src

#+RESULTS:
:results:
# Out[23]:
[[file:./obipy-resources/X8QvVE.svg]]
:end:

* Projectile motion
Our problem comes down to deciding whether the trajectory of a projectile intesects a line segment. Of course, we use the point particle simplification for the projectile.

In actuallity, the only routines we need for our basic purposes are ~get_horiz_position~ and ~score_check~, which are listed bellow. To begin with, ~get_horiz_position~ resorts to the kinematic equation
\[
y = y_0 + {v_y}_0 t - \frac12 gt^2
\]
which can be solved for $t$ as
 \[
t = \frac{{v_y}_0 \pm \sqrt{{{v_y}_0}^2 - 2g(y - y_0)}}{g}
\]
We discard the negative branch of the square root, for it yields points on the ascending part of the trajectory. Basically, the above equation gives us the parameter $t$ at which the the projectile would reach the height of the basket, and then evaluates its horizontal position at such time. Note that there is a problem with the first part of the statement, for the trajectory does not necessarily reaches all heights; such a situation will yield a complex value for $t$, and it shall also be interpreted as a failure in the condition. If the value of time is real, then we may proceed to evaluate whether or not the distance between the horizontal position and the centre of the line segment is between the radius of the latter.
#+begin_src ipython :session asession :exports code :results raw drawer
g = 9.8

def get_horiz_position(y_0, v_0, angle, y_ref) :
    try :
        with np.errstate(invalid='raise') :
            t = (v_0*np.sin(angle) + np.sqrt((v_0*np.sin(angle))**2 - 2*g*(y_ref - y_0))) / g
            _x = v_0*np.cos(angle)*t
            return _x
    except :
        _x = 'nan'
        return False

def score_check(y_0, v_0, angle, x_basket, y_basket, radius) :
    _x = get_horiz_position(y_0, v_0, angle, y_basket)
    if isinstance(_x, float) == True :
        return bool(np.abs(_x - x_basket) < radius)
    else :
        return False
#+end_src

#+RESULTS:
:results:
# Out[20]:
:end:

Now for visualisation purposes, we define the routine ~get_vert_position~ to calculate the vertical position of a set of points between 0 and the moment in which the horizontal position reaches the floor again. This allows us to graph the trajectory. This allows us to graph the trajectory.
#+begin_src ipython :session asession :exports both :results raw drawer
%config InlineBackend.figure_format = 'svg'
def get_vert_position(y_0, v_0, angle, x_ref) :
    t = x_ref / (v_0*np.cos(angle))
    _y = y_0 + v_0*np.sin(angle)*t - 0.5*g*t**2
    return _y

def plot(y_0, v_0, angle, x_basket, y_basket, radius) :
    _x = np.linspace(0, get_horiz_position(y_0, v_0, angle, 0), 40)
    _y = get_vert_position(y_0, v_0, angle, _x)

    if score_check(y_0, v_0, angle, x_basket, y_basket, radius) == True :
        plt.suptitle('It\'s a point!')
    else :
        plt.suptitle('Bad luck!')

    plt.gca().set_aspect('equal', adjustable='box')
    plt.xlabel('$x$')
    plt.ylabel('$y$')
    plt.title('Trajectory')
    plt.grid(True)
    plt.plot(_x,_y)
    plt.plot((x_basket - radius, x_basket + radius),(y_basket, y_basket))
    plt.show()

# Execute the code
plot(y_0 = 2,
     v_0 = 8,
     angle = np.pi/3,
     x_basket = 4,
     y_basket = 4,
     radius = 0.23)
#+end_src

#+RESULTS:
:results:
# Out[25]:
[[file:./obipy-resources/7fvF0L.svg]]
:end:
