# -*- coding: utf-8 -*-
"""actividad_01_lucas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9Jv9XVwx9P6KXwbKvffBscRM8G6dCOu
"""

def lucas(n):
  l = [2,1]
  if n > 2:
    while len(l) < n:
      suma = l[-1] + l[-2]
      l.append(suma)
  elif n == 1 :
    return l[0]
  elif n == 2 :
    return l[1]
  return l[-1]
print("Este es un script que retorna el n-ésimo término de la sucesión de Lucas")
n = int(input("ingrese el n-ésimo termino "))
r = lucas(n)
print(f"el {n} ésimo termino de la sucecion de lucas es {r}")