# -*- coding: utf-8 -*-
"""actividad_01_lucas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTDid9mwgCL4Gln9puy11V2kQeaSu9Ar
"""

def lucas(n):
  if n==0:
    return 2
  if n==1:
    return 1
  else:
    a = [2,1]
    for i in range (0,n):
      a.append(a[i]+a[i+1])
  return a[n]

print(lucas(3))
print(lucas(9))
print(lucas(10))
print(lucas(11))

