# -*- coding: utf-8 -*-
"""actividad_01_enteros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTDid9mwgCL4Gln9puy11V2kQeaSu9Ar
"""

a = int(input('Ingrese el valor del primer numero:'))
b = int(input('Ingrese el valor del segundo numero:'))
c = a/b
d = a%b

print(f'El resultado de la division es {c:.4}')
print('El residuo de la division es',d)

