# -*- coding: utf-8 -*-
"""actividad_01_doble_factorial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTDid9mwgCL4Gln9puy11V2kQeaSu9Ar
"""

def doble_factorial(n):
    l = []
    a = []
    for i in range(n):
        l.append(n-i)
    for i in range(0, len(l),2):
        a.append(l[i])
    b = a[0]
    for i in range(1, len(a)):
        b *= a[i]
    return b

print(doble_factorial(5))
print(doble_factorial(6))
print(doble_factorial(7))
print(doble_factorial(8))

