# -*- coding: utf-8 -*-
"""actividad_01_binomial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTDid9mwgCL4Gln9puy11V2kQeaSu9Ar
"""

# Primero creamos una funcion que nos calcule el factorial de un numero n
def factorial(n):
  if n == 0:
    return 1
  if n < 0:
    return 'El numero no puede ser negativo'
  if type(n) == float:
    return 'El numero debe ser entero'
  else:
    s = n
    while (n>1):
        n=n-1
        s=s*n
  return s

def binomial(n,k):
  m = factorial(n)
  q = factorial(k)
  d = factorial(n-k)

  c = m / (q * d)

  return c

print(binomial(5,3))
print(binomial(6,4))
print(binomial(7,2))

