# -*- coding: utf-8 -*-
"""Actividad 1_Punto3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ELQ-_cWYVojBdob913Q3KOPNgoXCsKZg

Actividad 01 Punto 3

Crea una función llamada lucas que reciba un parámetro llamado n. La función debe devolver el n-ésimo término de la sucesión de Lucas, que se define de forma similar a la sucesión de Fibonacci, pero con los dos primeros términos iguales a 2 y 1. Por ejemplo, si n es 3, la función debe devolver 4, que es el tercer término de la sucesión. Llama a la función lucas con diferentes valores para el parámetro n, como 9, 10 o 11.
"""

def lucas(n):
  if n == 0:
    return 2
  elif n == 1:
    return 1
  else:
      return(lucas(n - 1) +  lucas(n - 2))

k1 = lucas(9)
print(f"para 9 el valor es {k1}")

k2 = lucas(10)
print(f"para 10 el valor es {k2}")

k3 = lucas(11)
print(f"para 11 el valor es {k3}")