# -*- coding: utf-8 -*-
"""Actividad01_Punto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fg5EPwyDhkHKzGyIzcdfykBedly_sz3w

Actividad01 -Punto 1

Escribir un programa que pida al usuario dos números enteros , y muestre por pantalla el cociente y el residuo entre y
"""

#SE CREA UNA FUNCION CON DOS ARGUMENTOS , SON ENTEROS
def enteros(a,b):
  """
  esta funcion arroja el cociente y el residuo de dos enteros
  input: dos enteros a y b
  output: cociente y residuo

  """
  cociente = a/b
  residuo = a%b
  return cociente, residuo

# SE SOLICITA UN INPUT AL USUARIO
a = int(input("Escriba un numero entero "))
b = int(input("Escriba otro numero entero "))

cociente, residuo=enteros(a,b)

print("El cociente de la división  es ", cociente ,", el residuo de la división es ", residuo)

